name: Daily Job

on:
  # 定时触发：每天UTC时间的00:00执行
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 添加 workflow_dispatch 触发器

jobs:
  run_java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 设置 Java 环境
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 指定你需要的 Java 版本
          distribution: 'adopt'  # 指定 distribution 参数为 adopt 或其他有效值
          
      - name: 安装 Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: 构建 Java 项目
        run: mvn clean install  # 替换为你的项目构建命令

      - name: 构建项目
        run: mvn compile

      - name: 获取密码
        run: echo "export COOKIE=${{ secrets.MY_SECRET_PASSWORD }}" >> $GITHUB_ENV
        
      - name: 获取UID
        run: echo "export UID=${{ secrets.MY_SECRET_UID }}" >> $GITHUB_ENV

      - name: 运行 Java 程序
        run: java -cp src/main/java/com/xxl/job/executor/service com.xxl.job.executor.service.QuanMinKg $COOKIE $UID  # 替换为你的 Java 类的包路径和类名
