name: Daily Job

on:
  # 定时触发：每天UTC时间的00:00执行
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 添加 workflow_dispatch 触发器


jobs:
  run_java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 设置 Java 环境
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 指定你需要的 Java 版本

      - name: 获取密码
        run: echo "export PASSWORD=${{ secrets.MY_SECRET_PASSWORD }}" >> $GITHUB_ENV

      - name: 编译 Java 程序
        run: javac path/to/your_java_file.java  # 替换为你的 Java 文件的路径

      - name: 运行 Java 程序
        run: java -cp path/to your_java_file $PASSWORD  # 替换为你的 Java 类的包路径和类名
